### ISSUE TITLE
Google IO 2016 is broken on Firefox and IE.

### ISSUE THREAD

**Issue by pjmlp** [GoogleChrome/ioweb2016#1001]
Whenever I try to look up the schedule I am forced to use the mobile version instead of the desktop browsers I have access to.

![ff](https://cloud.githubusercontent.com/assets/608876/15418807/378fba70-1e62-11e6-8cf9-4291f5703df5.png)

![ie](https://cloud.githubusercontent.com/assets/608876/15418812/3d27c64e-1e62-11e6-96b5-98949bf44d9e.png)

**Comment by ebidel** [comment]
Can you be more specific? What browser, repo steps, etc?

**Comment by pjmlp** [comment]
Opening the website https://events.google.com/io2016/ is enough to reproduce the error.

Firefox ESR 31.8.0 and IE 11.0.9600.18282.

Firefox error console:
```
Content Security Policy: Unbekannte Direktive 'upgrade-insecure-requests' kann nicht verarbeitet werden
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create data:
```

Complains about _upgrade-insecure-requests_ not being known.

IE console doesn't show anything useful.

**Comment by ebidel** [comment]
FF 46 (current stable) works fine for me. The console warnings are just warnings and non-fatal.

I see the white page on ie 11 on a vm. The good news all the other pages work fine. The bad news is we're not going to have time to fix this for today :( If you could try another browser for today that would be great. Sorry!

We'll also be removing this page after today and it should start working again in IE11.
