### ISSUE TITLE
Featured Session cards don't show their background images

### ISSUE THREAD

**Issue by jungkees** [GoogleChrome/ioweb2016#1008]
Scenario:

1. Load https://events.google.com/io2016/
1. Scroll down to "Featured Session" area

Tested on: 
 - Samsung Internet 4.0 (Chromium 44.0.2403.133)
 - Chrome 43.0.2357.93

Expected behavior:
 - "Featured Session" cards render with their background images

Actual behavior:
 - "Featured Session" cards don't show any background images

In the "Elements" tab of the devtools, I found the following `style` attribute of the card-content div element in "io-home-page.html" is not applied:
`style="height:100%; background-image:url([[_computeBgImage(item)]])"`

**Comment by ebidel** [comment]
Those versions of chrome are fairly old. Can you confirm this is working on
newer browsers?

**Comment by ebidel** [comment]
Fixed via https://github.com/GoogleChrome/ioweb2016/commit/e9a6c4c216949ca6d484cfa08b6e802aa06ae339

**Comment by jungkees** [comment]
Thanks for the quick update!
