### ISSUE TITLE
error while compiling 

### ISSUE THREAD

**Issue by arangates** [GoogleChrome/ioweb2016#1015]
![screenshot from 2016-06-09 23-29-04](https://cloud.githubusercontent.com/assets/7692801/15940641/8ecc60b6-2e9a-11e6-9f49-fb1ba7f4c70d.png)

SyntaxError: Unexpected strict mode reserved word

**Comment by brendankenny** [comment]
What version of node are you using? That looks like the old v8 failure message before a number of es6 features, like `let`, were turned on by default. A number of es6 features are used in the project (even in just the gulpfile), so you'll need to update if you want to build.

Building will definitely work with Node 5 and later (just tried it). [`nvm`](https://github.com/creationix/nvm) can help with running multiple versions of node on one machine if you need to keep the older version around for other purposes.

**Comment by brendankenny** [comment]
@ebidel maybe we can add a minimum node version to the [list of requirements](https://github.com/GoogleChrome/ioweb2016#setup)?

**Comment by ebidel** [comment]
Doesn't https://github.com/GoogleChrome/ioweb2016/blob/master/package.json#L9 warn or something?

**Comment by brendankenny** [comment]
That's for npm, not node, so I believe you only get a warning if ioweb was on npm and you did `npm install ioweb2016`

**Comment by arangates** [comment]
yeah, i updated node.now theres is problem in starting Go server 
![screenshot from 2016-06-10 02-03-58](https://cloud.githubusercontent.com/assets/7692801/15945355/af07d134-2eaf-11e6-8ff2-3c83e18e72e8.png)

did i miss something?

**Comment by ebidel** [comment]
Looks like you have an older version of Go? https://github.com/GoogleChrome/ioweb2016#setup
