### ISSUE TITLE
404 Page -> Spelling error in title

### ISSUE THREAD

**Issue by lernerb** [GoogleChrome/ioweb2016#1026]
Ex. https://events.google.com/io2017

One of the `!` in the 404 page is actually a `1`. This seems to be an issue on any `events.google.com` web page - don't know who to direct this to. An alternative _short term solution_ would be to release the io17 page 😆 

Expected Title:

`<title>Error 404 (Not Found)!!1</title>`

Actual:

`<title>Error 404 (Not Found)!!1</title>`

**Comment by ebidel** [comment]
Haha nice find. We unfortunately do not control the top-level 404 pages. That's something that's handled by the domains team here at Google.

**Comment by ebidel** [comment]
It appears most Google 404 details pages of subdomains have this (e.g. https://chrome.google.com/webstore/detail/asdf). So it's possible the `1` is intentional or when they do fix it upstream, everyone will be fixed :)

Closing as we have no control over the domain config.

**Comment by lernerb** [comment]
Can we get a confirmation if this is intentional? :) Who would be the contact?
