### ISSUE TITLE
Firefox doesn't like our current service worker

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/ioweb2016#603]
Firefox is currently unhappy about something in our service worker script for Phase 3, leading to

```
Service worker registration failed: TypeError: ServiceWorker script at https://io-webapp-staging.appspot.com/io2016/service-worker.js for scope https://io-webapp-staging.appspot.com/io2016/ encountered an error during installation.
```

in the JS console in both `localhost` and the staging server. The production website's SW registration works fine in Firefox.

I'm going to see if there have been meaningful improvements to Firefox's SW debugging tools recently and try to track down what's going on.

**Comment by bsed** [comment]
firefox version :56.0 64
console 
`TypeError: ServiceWorker script at https://kelvin.mbioq.com/sw.js?v=570 for scope https://kelvin.mbioq.com/ encountered an error during installation.`

**Comment by marcusklaas** [comment]
Yup, this still happens. :/

**Comment by bsed** [comment]
@marcusklaas How did you solve this mistake?

**Comment by marcusklaas** [comment]
I didn't.. bug is still open I think.
