### ISSUE TITLE
VQA: Countdown icons

### ISSUE THREAD

**Issue by jcreech83** [GoogleChrome/ioweb2016#862]
- [ ] on desktop, the slanted decimals get clipped on the right side
![image](https://cloud.githubusercontent.com/assets/12943482/15081701/f406d782-1378-11e6-9e8a-98f63918052a.png)

- [ ] on chrome on an iphone 6s, some wider shapes are getting clipped on their right sides

- [ ] remove the time units as well as the unit separators. So, it’ll just be the objects moving around.

@tdreyno

**Comment by ebidel** [comment]
Closing.
