### ISSUE TITLE
Clicking Fullscreen on the Live Stream on makes the video all white.

### ISSUE THREAD

**Issue by jmsgomes** [GoogleChrome/ioweb2016#967]
How to reproduce:
*   https://events.google.com/io2016/
*   Click the Fullscreen icon in the player controls.

Actual result:
<img width="1440" alt="screen shot 2016-05-18 at 10 18 54 am" src="https://cloud.githubusercontent.com/assets/3680160/15368325/0c9b8f00-1ce2-11e6-9bd3-ed6827261190.png">

Expected result:
The live stream full screen.

**Comment by ebidel** [comment]
We disabled fs
