### ISSUE TITLE
[Cosmetic] Live Schedule (from FAB) lists sessions that are live also under "Upcoming" tab

### ISSUE THREAD

**Issue by jmsgomes** [GoogleChrome/ioweb2016#974]
Clicking on these actually-live sessions under the "Upcoming" tab opens up an embedded player for the live stream, which is neat as a Picture-In-Picture preview, but also moderately confusing because, to actually switch over to that live stream as the "main picture", I still have to click the "Live" tab, and select the session from there.

**Comment by ebidel** [comment]
This is wai
