### ISSUE TITLE
While the "added to your schedule" toast is up, I can't click outside of the modal dialog to dismiss

### ISSUE THREAD

**Issue by dragon788** [GoogleChrome/ioweb2016#980]

**Comment by ebidel** [comment]
This is WAI. The toast is a layer which gains focus and allows users to dismiss it with keyboard.

**Comment by dragon788** [comment]
Ahh, I can use Esc to dismiss the toast and then I can click outside of the
modal window? This kind of breaks my mouse flow, but I can understand that.
