### ISSUE TITLE
Phase 5 bugs

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/ioweb2016#981]
- the countdown is stuck in super fast fun mode
- the keynote card doesnt launch the video
- most of the featured video cards dont launch a video

**Comment by jcreech83** [comment]
@tdreyno can you look into the countdown piece? 
https://io-webapp-staging.appspot.com/io2016/

**Comment by ebidel** [comment]
My cpu is clocking 100%.

**Comment by paulfarning** [comment]
Keynote video id property was missing the `$=`. PR for that fix.

The other videos currently aren't getting a video. Is theYoutube id still missing from the data source?

**Comment by ebidel** [comment]
Good point. Looks like all the featured ones are still streaming ids. They need to update the CMS to the full yt url

**Comment by ebidel** [comment]
Going to  close this.
