### ISSUE TITLE
Not able to change resolution!

### ISSUE THREAD

**Issue by coolamz** [GoogleChrome/ioweb2016#986]
Using 'Chrome 50.0.2661.102 m' on my Dell 3148 (11.6 inch) running on Windows 10. I'm not able to change resolution to 240p,360p, 480p via mouse pointer. Had to use TAB key on my keyboard. Not able to click 240p,360p, 480p options via mouse pointer.

**Comment by ebidel** [comment]
Is this related to https://github.com/GoogleChrome/ioweb2016/issues/968?
