### ISSUE TITLE
QA Ph5: Homepage - Issues loading complete content 

### ISSUE THREAD

**Issue by brittasinnott** [GoogleChrome/ioweb2016#989]
Unable to load the complete page contents on some browsers.  Only the countdown, an empty video tile and the description of Google I/O (in the blue box) appear.  This is reproducible in a signed in and signed out state after clearing the cache multiple times and on two  machines running OS X 10.11. I've attached a screenshot that includes the console log for reference. 

Steps: 
1. Clear browsers cache 
2. Go to staging
3. Note that complete content is not loaded 

Browsers: 
Chrome 50 Mac OS X 10.11 
Firefox 46 Mac OS X 10.11 

![gio_989](https://cloud.githubusercontent.com/assets/15128124/15411399/8dc9fee8-1dd4-11e6-818f-31c39888714b.png)

**Comment by brittasinnott** [comment]
Reproducible on Google Nexus 5 - Android 5.1.1 - Chrome.

**Comment by ebidel** [comment]
Can you try to do a hard refresh and make sure you're logged in to the page. I also pushed some changes that may have fixed some of these issues. Please reopen if you still see issues.

**Comment by brittasinnott** [comment]
Hi @ebidel this issue seems to be cleared up.  Thanks!
