### ISSUE TITLE
QA Ph5: Homepage - Videos fail to play

### ISSUE THREAD

**Issue by brittasinnott** [GoogleChrome/ioweb2016#990]
Most of the Featured Session videos and Key Note video have an error when user attempts to play them. 

Steps: 
1. Go to https://io-webapp-staging.appspot.com/io2016/
2. Click to play a Featured Session video 
3. Note error 

Safari 9 Mac OS X 10.11 
MS Edge Windows 10

![gio_990](https://cloud.githubusercontent.com/assets/15128124/15412000/13506922-1dd9-11e6-9e30-c6bd4c701ed2.png)

**Comment by ebidel** [comment]
We don't have video urls from the CMS yet. This will fix itself.
