### ISSUE TITLE
QA PH5: Homepage - Truncated content on browser resize 

### ISSUE THREAD

**Issue by brittasinnott** [GoogleChrome/ioweb2016#992]
When the browser window is reduced in size, the text in the Google I/O description box becomes truncated at the bottom.  See screenshot for reference. 

Steps: 
1. Go to staging
2. Reduce browser window size 
3. Note truncated text 

MS Edge Windows 10 

![gio_992](https://cloud.githubusercontent.com/assets/15128124/15413336/fdf96b68-1de3-11e6-8872-0087a65dd5ee.PNG)

**Comment by ebidel** [comment]
@paulfarning can you take this?

**Comment by ebidel** [comment]
This should be fixed.
