### ISSUE TITLE
Phase 5: Quote card

### ISSUE THREAD

**Issue by ldalepaves** [GoogleChrome/ioweb2016#993]
Decrease the size of the quote card so that it's not so gigantic 
![screen shot 2016-05-19 at 4 27 36 pm](https://cloud.githubusercontent.com/assets/16674821/15412736/d01938a4-1dde-11e6-9fe2-dbb7f3e4fb14.png)

**Comment by ebidel** [comment]
fyi @jcreech83

**Comment by ldalepaves** [comment]
this is no longer relevant given bug #996
