### ISSUE TITLE
Phase 5: Updates to page layout

### ISSUE THREAD

**Issue by ldalepaves** [GoogleChrome/ioweb2016#996]
Reviewing Phase 5 with mpegg and we'd like to make some changes. 

1. Replace the first copy card with the see all videos card
2. Replace current "see all videos card" with VR, and replace current VR slot with this firebase session
2. Delete the middle quote card all together and just move up the bottom cards

**Comment by jcreech83** [comment]
@paulfarning can you take care of this?

**Comment by jcreech83** [comment]
Believe Eric took care of the 1. 

The Firebase session to add is this one - https://events.google.com/io2016/schedule?sid=322d2aeb-0bef-e511-a517-00155d5066d7#day1/322d2aeb-0bef-e511-a517-00155d5066d7

**Comment by paulfarning** [comment]
@ebidel Should we be hardcoded these sessions into the grid rather than pull from the schedule data?

**Comment by ebidel** [comment]
Yea I think that would be better. We lose the ability to automatically pull the new featured sessions from the API, but I don't think they'll be changing much after today.

**Comment by ebidel** [comment]
@falcober @ldalepaves are going to get us a semi-final list of featured sessions we can hardcode. We agreed to randomize their order (current behavior in master) so they load in different places on every page load.

**Comment by jcreech83** [comment]
Here's the list that was provided previously along with new FB session brought up yesterday. Any changes?

AN10: What's new in Android (Weds)
FB14: Firebase Overview (Weds)
VR1: VR at Google (Thurs)
 PL14: What's new in Google Play for Devs (Thurs)
MW68: The Mobile Web State of the Union (Thurs)
SR7: Google's Vision for Marchine Learning (Friday)
Use Firebase analytics to build a brilliant app

**Comment by ebidel** [comment]
The session ids will be in https://events.google.com/io2016/api/v1/schedule

**Comment by paulfarning** [comment]
@ebidel If randomizing the order, is there still need to hardcode rather than pull from schedule.json data? I was asking earlier when sounded like wanted specific sessions to land in specific slots.

**Comment by ebidel** [comment]
That's true. Guess it's easier to keep pulling from schedule data. No
changes need to be made, right?

**Comment by paulfarning** [comment]
PR with the other layout updates is in. Left the loading and arranging of feature sessions alone.
